### ISSUE TITLE
希望加入司机的twitter用户名或者昵称

### ISSUE THREAD

**Issue by veeoni** [johnmave126/garupa_car#2]
有时候发现一位好司机，并没有太多信息记住这位司机。
如果加一列，专门显示用户名，感觉会更好~

**Comment by johnmave126** [comment]
现在有一个功能是要进房时点一下那一行，会把那一行置顶，打完以后可以对这个房间进行评分呢（顶/踩），这个信息会存在本地，这个司机的所有房间会共享评分，在最左边一栏体现。
看来好像不是很直观...过两天我把司机名加上吧。
